# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rachel Viniar
email: rviniar@gmail.com
description: "Rachel Viniar is an office manager turned IT admin with a general love of organization and data (and games). This is her blog, where she talks about those things and probabably other stuff too."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rachelviniar.com" # the base hostname & protocol for your site
permalink: /:title/
author: Rachel Viniar
future: false

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
